import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Providers from "./Providers";
import { ClerkProvider } from "@clerk/nextjs";
import { Mali } from 'next/font/google'
import { Suspense } from "react";

const mali = Mali({
  weight: '400',
  subsets: ['latin', 'thai']
})




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${mali.className} antialiased`}
        >      <Suspense>

            <Providers>
              <Navbar />
              <main className="container">{children}</main>
            </Providers>
          </Suspense>
        </body>
      </html>
    </ClerkProvider>
  );
}